[package]
name = "megagame-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
reqwest = "0.11.4"
serde = "1.0.126"
serde_json = "1.0.65"
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "cache", "unstable_discord_api"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
clap = { version = "2.33", default-features = false, features = ["suggestions", "vec_map"] }
tracing = "0.1"
tracing-subscriber = "0.2"