[package]
name = "megagame-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
reqwest = "0.11.9"
serde = "1.0.136"
serde_json = "1.0.78"
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "cache", "unstable_discord_api"] }
tokio = { version = "1.16.1", features = ["macros", "rt-multi-thread"] }
clap = { version = "3.0.14", default-features = true}
tracing = "0.1"
tracing-subscriber = "0.3.7"
sys-info = "0.9"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
sea-orm = { version = "0.5.0", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros", "with-chrono", "sqlx-postgres" ], default-features = false }
