//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

pub use super::{
    currency::Entity as Currency, player::Entity as Player, post::Entity as Post,
    task::Entity as Task, team::Entity as Team, wallet::Entity as Wallet,
};
