//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "team"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub name: String,
    pub abreviation: Option<String>,
    pub guild: Option<i32>,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
    pub emoji: Option<String>,
    pub wallet: Option<i32>,
    pub role: Option<i32>,
    pub category_id: Option<i32>,
    pub general_channel_id: Option<i32>,
    pub trade_channel_id: Option<i32>,
    pub menu_channel_id: Option<i32>,
    pub bank_embed_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Abreviation,
    Guild,
    CreatedAt,
    UpdatedAt,
    Emoji,
    Wallet,
    Role,
    CategoryId,
    GeneralChannelId,
    TradeChannelId,
    MenuChannelId,
    BankEmbedId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Category,
    Channel3,
    Channel2,
    Channel1,
    Player,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(None).def(),
            Self::Abreviation => ColumnType::String(None).def().null(),
            Self::Guild => ColumnType::Integer.def().null(),
            Self::CreatedAt => ColumnType::String(None).def().null(),
            Self::UpdatedAt => ColumnType::String(None).def().null(),
            Self::Emoji => ColumnType::String(None).def().null(),
            Self::Wallet => ColumnType::Integer.def().null(),
            Self::Role => ColumnType::Integer.def().null(),
            Self::CategoryId => ColumnType::Integer.def().null(),
            Self::GeneralChannelId => ColumnType::Integer.def().null(),
            Self::TradeChannelId => ColumnType::Integer.def().null(),
            Self::MenuChannelId => ColumnType::Integer.def().null(),
            Self::BankEmbedId => ColumnType::Integer.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Category => Entity::belongs_to(super::category::Entity)
                .from(Column::CategoryId)
                .to(super::category::Column::Id)
                .into(),
            Self::Channel3 => Entity::belongs_to(super::channel::Entity)
                .from(Column::MenuChannelId)
                .to(super::channel::Column::Id)
                .into(),
            Self::Channel2 => Entity::belongs_to(super::channel::Entity)
                .from(Column::TradeChannelId)
                .to(super::channel::Column::Id)
                .into(),
            Self::Channel1 => Entity::belongs_to(super::channel::Entity)
                .from(Column::GeneralChannelId)
                .to(super::channel::Column::Id)
                .into(),
            Self::Player => Entity::has_many(super::player::Entity).into(),
        }
    }
}

impl Related<super::category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Category.def()
    }
}

impl Related<super::player::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Player.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
