//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "team"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub name: String,
    pub abreviation: Option<String>,
    pub created_at: Option<Date>,
    pub updated_at: Option<Date>,
    pub emoji: Option<String>,
    pub wallet: Option<i32>,
    pub fk_bank_embed_id: Option<i32>,
    pub fk_guild_id: Option<i64>,
    pub fk_team_role_id: Option<i64>,
    pub fk_team_category_id: Option<i64>,
    pub fk_general_channel_id: Option<i64>,
    pub fk_trade_channel_id: Option<i64>,
    pub fk_menu_channel_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Abreviation,
    CreatedAt,
    UpdatedAt,
    Emoji,
    Wallet,
    FkBankEmbedId,
    FkGuildId,
    FkTeamRoleId,
    FkTeamCategoryId,
    FkGeneralChannelId,
    FkTradeChannelId,
    FkMenuChannelId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Category,
    Channel3,
    Channel2,
    Channel1,
    Guild,
    Player,
    Role,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(None).def(),
            Self::Abreviation => ColumnType::String(None).def().null(),
            Self::CreatedAt => ColumnType::Date.def().null(),
            Self::UpdatedAt => ColumnType::Date.def().null(),
            Self::Emoji => ColumnType::String(None).def().null(),
            Self::Wallet => ColumnType::Integer.def().null(),
            Self::FkBankEmbedId => ColumnType::Integer.def().null(),
            Self::FkGuildId => ColumnType::BigInteger.def().null(),
            Self::FkTeamRoleId => ColumnType::BigInteger.def().null(),
            Self::FkTeamCategoryId => ColumnType::BigInteger.def().null(),
            Self::FkGeneralChannelId => ColumnType::BigInteger.def().null(),
            Self::FkTradeChannelId => ColumnType::BigInteger.def().null(),
            Self::FkMenuChannelId => ColumnType::BigInteger.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Category => Entity::belongs_to(super::category::Entity)
                .from(Column::FkTeamCategoryId)
                .to(super::category::Column::DiscordId)
                .into(),
            Self::Channel3 => Entity::belongs_to(super::channel::Entity)
                .from(Column::FkGeneralChannelId)
                .to(super::channel::Column::DiscordId)
                .into(),
            Self::Channel2 => Entity::belongs_to(super::channel::Entity)
                .from(Column::FkMenuChannelId)
                .to(super::channel::Column::DiscordId)
                .into(),
            Self::Channel1 => Entity::belongs_to(super::channel::Entity)
                .from(Column::FkTradeChannelId)
                .to(super::channel::Column::DiscordId)
                .into(),
            Self::Guild => Entity::belongs_to(super::guild::Entity)
                .from(Column::FkGuildId)
                .to(super::guild::Column::DiscordId)
                .into(),
            Self::Player => Entity::has_many(super::player::Entity).into(),
            Self::Role => Entity::belongs_to(super::role::Entity)
                .from(Column::FkTeamRoleId)
                .to(super::role::Column::DiscordId)
                .into(),
        }
    }
}

impl Related<super::category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Category.def()
    }
}

impl Related<super::guild::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Guild.def()
    }
}

impl Related<super::player::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Player.def()
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Role.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
